import streamlit as st
import quiz_generator
from quiz_generator import generate_quiz

st.set_page_config(page_title="AI Quiz Generator", layout="centered")
st.title("🤖 AI Quiz Generator")
st.write("Enter a topic and take a quiz generated by AI!")

topic = st.text_input("Enter a topic (e.g. Python, History, Space)")

if st.button("Generate Quiz") and topic:
    with st.spinner("Generating quiz..."):
        quiz_text = generate_quiz(topic)
        st.session_state.quiz_data = quiz_text.strip().split("\n\n")
        st.session_state.current_q = 0
        st.session_state.score = 0

if "quiz_data" in st.session_state and st.session_state.current_q < len(st.session_state.quiz_data):
    question_block = st.session_state.quiz_data[st.session_state.current_q].splitlines()
    question_lines = [line for line in question_block if not line.startswith("Correct Answer")]
    correct_line = [line for line in question_block if line.startswith("Correct Answer")][0]
    correct_answer = correct_line.split(":")[1].strip().upper()

    st.subheader(f"Question {st.session_state.current_q + 1}")
    for line in question_lines:
        st.write(line)

    choice = st.radio("Choose an answer:", ['A', 'B', 'C', 'D'])

    if st.button("Submit Answer"):
        if choice == correct_answer:
            st.success("✅ Correct!")
            st.session_state.score += 1
        else:
            st.error(f"❌ Wrong. Correct answer: {correct_answer}")
        st.session_state.current_q += 1

elif "quiz_data" in st.session_state and st.session_state.current_q >= len(st.session_state.quiz_data):
    st.success(f"🎉 Quiz Complete! Your score: {st.session_state.score}/{len(st.session_state.quiz_data)}")
    if st.button("Start New Quiz"):
        st.session_state.clear()
